from fastapi import APIRouter, Depends
from src import LOGGER
from src import fire_utils
from src.app_utils import api_key_required
from src.models import Profile

router = APIRouter(prefix="/fake")

existing_people = [
    {
        "name": "Sara",
        "persona": 'Based on the conversation transcript provided, they appear to be a well-rounded individual with a variety of interests and passions that shape their personality profile:\n\n1. Music Enthusiast: Their love for music spans across genres such as Indie, pop, and Flamenco. She enjoys attending live music events and recently found great enjoyment in a Paula Mattheus concert. This suggests that music is an important aspect of their life, indicating a creative and expressive side to their personality.\n\n2. Travel Enthusiast: They have a strong passion for traveling, with Senegal and Gambia being standout destinations for them due to the diverse cultures, landscapes, lifestyle, and activities they offer. She is also intrigued by the idea of visiting Polynesia, showcasing their curiosity for new experiences and appreciation for exploration.\n\n3. Literary Enthusiast: They enjoy reading novels and real stories, with "Violeta" by Isabel Allende currently catching their attention. Her preference for exploring different narratives and perspectives through reading suggests an open-minded and introspective nature.\n\n4. Social Mediator: Their background in social mediation reflects their commitment to contributing positively to society and finding fulfillment through making a difference in people\'s lives. This indicates a caring, empathetic, and altruistic aspect of their personality.\n\nOverall, they come across as a multifaceted individual who values creativity, exploration, knowledge, and contribution to society. Her interests in music, travel, literature, and social mediation highlight a well-rounded personality with a zest for life and a desire to make a meaningful impact on the world.',
    },
    {
        "name": "Jordan Killen",
        "persona": "Based on the conversation transcript provided, I have distilled the following personality profile:\n\nThey are a passionate traveler who values exploring destinations that offer a mix of stunning natural beauty and vibrant city life. Their favorite place visited so far is Sorrento, Italy, where they were captivated by the clear waters and amazing views. Dreaming of traveling to Sydney, Australia next, they desire a blend of city excitement and beach tranquility.\n\nIn terms of music, they love attending live concerts, with Drake being their all-time favorite artist to see perform live. Their interest in sports lies in Formula 1, particularly admiring Max Verstappen's skills on the track.\n\nOutside of these interests, they enjoy staying active with hobbies like sailing in Malahide, longer cycles, and shorter runs. They find joy in challenges and varied outdoor activities. When it comes to relationships, they value trust, adventure, and humor in an ideal partner.\n\nOverall, their personality can be described as adventurous, active, and appreciative of experiences that offer a combination of excitement and natural beauty. They value shared interests and qualities such as trust and humor in their relationships. Matching with someone who shares their passions for travel, music, sports, and outdoor activities would likely make for a fulfilling connection.",
    },
    {
        "name": "Robin Caird",
        "persona": "### Personality Profile:\n\nA well-rounded individual with a diverse range of interests and a genuine passion for exploring various aspects of life. \n\n- **Cooking:** They enjoys cooking Italian and Asian dishes and finds joy in preparing meals for others, showcasing a caring and nurturing side to their personality. Cooking for others is not just a task but a way to connect and bring people together, emphasizing their sociable nature.\n\n- **Music:** With a mixed taste in music including rap, rock, and jazz, they appreciate diversity and is open to different genres, reflecting an open-minded and adaptable personality.\n\n- **Travel:** They prefer a balance between relaxing vacations and adventurous trips like sailing or fishing, showing a blend of appreciation for both excitement and serenity, demonstrating an adaptable and versatile approach to new experiences.\n\n- **Career:** As a medical student interested in plastic surgery, they exhibit dedication and a desire for challenges and personal growth. The field they are drawn to requires precision, creativity, and a strong focus on aesthetics, indicating a meticulous and ambitious nature.\n\n- **Partner Preferences:** they seek a partner who shares similar interests in travel but is open to learning and experiencing new things together. They value shared values and compatible personalities over specific interests, showing a willingness to explore and broaden their horizons. While preferring a similar level of education in their partner, they are open to someone outside the medical field, signaling a desire for diversity and balance in their relationships.\n\nOverall, their personality can be described as sociable, open-minded, adaptable, ambitious, and caring, making them an engaging and well-rounded individual who values connections, growth, and shared experiences in relationships.",
    },
    {
        "name": "Lorna",
        "persona": "Personality Profile:\n\nA passionate and creative individual with a deep love for art, specifically painting, drawing, and pottery. She not only appreciates art but also enjoys creating their own pieces, showcasing their artistic talent and expression. They value independence in their interests and appreciates a partner who respects their dedication to art while also having their own hobbies.\n\nIn addition to art, their interests extend to traveling, where they seek a partner who shares their enthusiasm for exploring new destinations and creating lasting memories together. Her favorite travel spot is New York, highlighting their appreciation for vibrant and diverse urban experiences. They enjoy a mix of adventurous activities and cultural exploration while traveling, demonstrating their curiosity and openness to new experiences.\n\nWhen it comes to relationships, they prioritize building a strong emotional connection and mutual trust with their partner. While they enjoy trying new things and embarking on adventures, they value the stability and depth that come from an emotional bond. Their ideal partner would introduce them to new experiences while understanding the importance of trust and emotional intimacy in a long-term relationship.\n\nOverall, they are a creative, adventurous, and emotionally grounded individual who values art, travel, and strong connections in their relationships. She seeks a partner who shares their passions and values, ready to embark on new adventures and create meaningful experiences together.",
    },
    {
        "name": "Robyn",
        "persona": "Based on the conversation transcript provided, here is a distilled personality profile for the user:\n\They are a warm and engaging individual who enjoys immersing herself in romance novels, particularly by authors like Taylor Jenkins Reid. She values variety in their travel experiences, being open to both adventurous destinations and relaxing beach resorts depending on the time of year. \n\nIn their professional life as a People Operations Partner, they find fulfillment in working closely with others and supporting them in their daily tasks. She has clear ambitions of becoming a people manager in HR, showcasing their passion for personal development and leadership roles.\n\nWhen it comes to food preferences, they delight in trying new restaurants and cuisines, indicating their adventurous and curious nature. Communication and honesty are paramount for them in relationships, as they recognize them as crucial elements for building strong and meaningful connections.\n\nIn terms of partner preferences, they seek individuals who are similar in age and share similar morals. While open to differing interests and thoughts, shared values and morals are non-negotiable for them in a partner.\n\nOverall, they come across as a compassionate, open-minded, and goal-oriented individual who values personal connections, professional growth, culinary adventures, and meaningful relationships built on communication and honesty.",
    },
    {
        "name": "Alex Johnson",
        "persona": "Based on the conversation transcript provided, their personality can be distilled into the following profile:\n\n1. **Passionate Technophile:** They shows a strong interest in cutting-edge technology, particularly machine learning and artificial intelligence. He is fascinated by the potential of AI to enhance our lives and finds inspiration in areas such as biology and robotics.\n\n2. **Adventurous Spirit:** They enjoys adventure-packed trips and trying new experiences. He recently engaged in activities like hiking, skiing, and scuba diving, indicating a love for challenging and exciting adventures.\n\n3. **Active and Athletic:** They are into sports and physical activities, actively participating in tennis and rock climbing. He also has a keen interest in watching tennis matches live, highlighting his enthusiasm for sports both as a player and a spectator.\n\n4. **Ambitious and Driven:** In terms of personal relationships, they are looking for a partner who shares his passion for career and is driven to succeed in life. He values ambition and seeks someone who is supportive of his goals and aspirations.\n\nOverall, they appear to be a tech-savvy, adventurous, active, and ambitious individual who is seeking a partner with similar values and goals. His ideal match would likely be someone who shares his enthusiasm for science, adventure, sports, and success in their careers.",
    },
    {
        "name": "Covi",
        "persona": "Based on the conversation transcript provided, here is a detailed personality profile for the user:\n\They are a multifaceted individual with a diverse range of interests and passions. They have a sophisticated taste in music, enjoying genres like R&B, Spanish music, and indie pop, indicating a creative and eclectic music taste. They have a keen interest in traveling, having a fondness for Japan and a dream to visit Vietnam, showcasing a love for exploring new cultures and places.\n\nIn the kitchen, they find joy in baking and preparing Spanish dishes, reflecting a mix of creativity and cultural appreciation in their culinary endeavors. As a PhD student focused on cancer research, they possess a curious and inquisitive mind, with a personal connection to the field through their family history, showcasing empathy and dedication to making a difference.\n\nIn terms of relaxation, they find solace in social activities like walks, coffee with friends, painting, chatting on the phone, and listening to music, highlighting a balanced approach to unwinding after a busy day of academic pursuits.\n\nWhen it comes to relationships, they value qualities such as a strong connection to family and friends, a love for exploration and learning, commitment, supportiveness, and independence in a potential partner, indicating a desire for a deep and meaningful connection with someone who shares similar values and interests.\n\nOverall, they emerge as a well-rounded individual with a blend of creativity, curiosity, empathy, and a strong sense of connection to both their personal and academic pursuits. Their diverse range of interests and values make them an intriguing and engaging individual to connect with on a deeper level.",
    },
    {
        "name": "Jack M",
        "persona": "Based on the conversation transcript provided, here is a personality profile:\n\They are a multi-faceted individual with a deep appreciation for emotive and heartfelt music, particularly indie folk, rock, and acoustic genres. His love for lyrical songs that delve into feelings reflects his introspective and sensitive nature. Playing the guitar and teaching himself piano showcase his creative and musical talents, highlighting his passion for self-expression through music.\n\nIn terms of reading interests, their eclectic taste ranges from self-improvement and philosophy to high fantasy and pop science, reflecting his intellectual curiosity and desire for both personal growth and escapism. His career as a PhD researcher suggests a strong analytical mindset and a keen interest in scientific topics.\n\Their affinity for outdoor spaces like Yosemite reveals his adventurous spirit and longing for a deep connection with nature. He finds solace and rejuvenation in the great outdoors, emphasizing his appreciation for tranquility and natural beauty.\n\nHis passion for running and middle-long distance competitions portrays his disciplined and determined nature, as well as his drive for self-improvement and pushing personal boundaries. Their dedication to improving his abilities in sports reflects his commitment to growth and achievement.\n\nIn the kitchen, they showcase their culinary skills with a love for Italian and Mexican cuisines, favoring hearty and spicy flavors. His enjoyment of cooking these dishes suggests a creative and experimental approach to food, showcasing his passion for flavors and exploration.\n\nOverall, they are a thoughtful, creative, and intellectually curious individual with a deep connection to nature, a drive for self-improvement, and a passion for music, sports, and culinary exploration. His diverse interests and talents make them a well-rounded and engaging individual with plenty to offer in a potential relationship.",
    },
    {
        "name": "Jack Hussey",
        "persona": "Based on the conversation transcript provided, here is a personality profile:\n\They are an adventurous individual who has a strong passion for travel, expressing a desire to visit the South of France in the future. He also shows an interest in sports, particularly favoring the UFC. His eclectic taste in music spans across various genres, indicating an open-minded and versatile nature. Their preference for reading books published by Penguin Publishing suggests a sophisticated literary taste. When it comes to art, they appreciate creative endeavors without having a specific favorite artist or style.\n\They appear to be a well-rounded and culturally aware individual with a diverse range of interests. He values creativity and enjoys exploring different forms of art and entertainment. Their preference for a partner with similar interests suggests that they value shared hobbies and experiences in relationships.\n\nOverall, they come across as a dynamic and engaging individual with a zest for life and exploration. His open-mindedness and appreciation for diverse experiences make them a fascinating potential match for someone who shares his sense of adventure and curiosity.",
    },
    {
        "name": "Sofia Miron Barroso",
        "persona": "### Personality Profile:\n\nA well-rounded individual with a deep appreciation for balance in life. She values exploring new cultures and seeking adventure while also enjoying moments of relaxation. Their passion lies in the field of biomedical sciences, particularly in materials science and cancer biology, where they aim to make a positive impact on people's health through technology.\n\nIn their reading preferences, they gravitate towards non-fiction books to satisfy their thirst for knowledge, especially in science, history, and productivity. She also enjoys fiction genres like sci-fi and mystery. When it comes to leisure activities, they find solace in outdoor pursuits, such as hiking in the mountains and swimming in the sea, embracing the rejuvenating power of nature.\n\nIn terms of food, they follow a Mediterranean vegan diet, reflecting their Spanish roots and ethical choices. While they enjoy trying new cuisines when time permits, they have their go-to meals for daily sustenance. Their music taste leans towards not having a strong preference for any particular genre, showcasing their diverse interests.\n\Their travel experiences have taken them to captivating destinations like Tanzania, Peru, Jordan, and Greece, with a desire to explore Southeast Asia, Australia, and beyond. She values shared values and interests like ambition, career-drive, and a love for travel in a potential partner, while also appreciating differences to foster mutual learning and growth.\n\nEducation holds significant importance for them, as they seek a partner with a similar educational background to align with their values of ambition, curiosity, and a passion for continuous learning. Their openness to new experiences and their well-rounded personality make them an intriguing and dynamic individual, ready to connect with like-minded individuals on their dating journey.",
    },
    {
        "name": "David",
        "persona": 'Based on the conversation transcript provided, here is a personality profile for them:\n\nA strategic thinker who enjoys intellectual challenges, as evidenced by his interest in playing chess. He values staying active and connecting with nature through activities like hiking, particularly in picturesque locations like the Alps. They have a musical preference for bands like Coldplay and enjoys attending concerts to experience live music. While they havn\'t been to a Coldplay concert yet, they appreciate the thrill of live performances. In terms of entertainment, they are drawn to TV shows with intense storylines and deep themes, such as "Breaking Bad" and "The Handmaid\'s Tale." His interest in psychology, particularly in the work of Daniel Kahneman, reflects a curiosity for deep topics and meaningful conversations. They value a potential partner who shares his love for the outdoors, indicating that they seek compatibility in interests and lifestyle choices.\n\nOverall, their personality can be described as intellectually curious, nature-loving, and appreciative of deep conversations and experiences. He values activities that challenge them mentally and physically, and seeks a partner who shares his passion for outdoor adventures.',
    },
]


@router.get("/people", dependencies=[Depends(api_key_required)])
def add_fake_person():
    # adds 2 x 3 people per fake profile
    for person in existing_people:
        persona = person["persona"]
        for _ in range(3):
            for gender in ["Male", "Female"]:
                profile = Profile.generate_random(gender=gender)
                fire_utils.save_profile(profile.user_id, profile)
                fire_utils.save_persona(profile.user_id, persona)
                LOGGER.info(f"Fake profile added: {profile.user_id}")
    return {"message": "Fake people added"}
